version: "3.9"

services:
  api: &api
    build:
      context: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - auth-network

  redis:
    image: redis:alpine
    container_name: auth_cache
    ports:
      - "6379:6379"
    networks:
      - auth-network


networks:
  auth-network:
    driver: bridge